### ISSUE TITLE
Bnd_Box and surface creation errors with CurvedArray

### ISSUE THREAD

**Issue by ofpkubi** [chbergmann/CurvedShapesWorkbench#27]
Hi,

There are some error messages that I can't rid of using the newest version of your workbench (not manual install though) in FreeCAD 0.21.2 and 0.22dev version.

There are no visual errors, but I'm concerned that moving forward with it would break something later on.

```
22:48:53  16Standard_Failure Need at least two vertices, edges or wires to create loft face
22:48:53  Creation of surface is not possible !
22:48:53  <Part> ViewProviderExt.cpp(1278): Cannot compute Inventor representation for the shape of Hull__CurvedArrayErrors#CurvedArray002: Bnd_Box is void

22:48:53  <Part> ViewProviderExt.cpp(1278): Cannot compute Inventor representation for the shape of Hull__CurvedArrayErrors#CurvedArray: Bnd_Box is void

22:48:53  <Part> ViewProviderExt.cpp(1278): Cannot compute Inventor representation for the shape of Hull__CurvedArrayErrors#CurvedArray003: Bnd_Box is void
```
I have 3 Curved Arrays in my model. 

The first one is a solid. Note that the error is the same with surface instead of body.

The second and third are just generating the cross-sections. 
The second has Part:ExplodeCompound and a Part:Loft on the sections. This way, I have avoided the surface creation error that I had with the first...

I know that, strictly speaking, it is not needed, but I am using Draft:Clone of sketches (to reuse) properly as the cross-section and sometimes for bounding curves too in the CurvedArray. Can this be the problem?

Here is my model (a bit complex, so I try to reproduce the problem with something simpler later on):
[Hull__CurvedArrayErrors.FCStd.gz](https://github.com/chbergmann/CurvedShapesWorkbench/files/14426201/Hull__CurvedArrayErrors.FCStd.gz)

**Comment by ofpkubi** [comment]
Created a simpler file. Now it is without a Draft:Clone, and with only one shape.

The problem still exists.

[CurvedShapesError.zip](https://github.com/chbergmann/CurvedShapesWorkbench/files/14466242/CurvedShapesError.zip)

**Comment by nicocesar** [comment]
I'm having the same issue. Anyone came up with a workaround?

**Comment by AIRCAP** [comment]
My suspicion.is, this hapens when a file with curvedshapes loafs from disk, recompute is called before the parts are actually rendered. CurvedSurface relies on the.part BoundBox property, but that is not relyable until a part is tesselated, which happens when its displayed on screen. When the entire document is recomputed later, the part boundingboxes are corrext, therefore the error message only appears on freecad startup respectively when a file is first loaded.

The workaround is to recompute the whole document ( right click documentvroot node in tree, select mark for recompute, then "recompute" (ctrl+r)

A fix could include triggering manual tesselation of anything the boundingbox is needed ( usually the end shape wires/sketches and hullcurves) but doing that on every recompute could slow things down

**Comment by AIRCAP** [comment]
Here is a backtrace:

```
12:23:10  16Standard_Failure Need at least two vertices, edges or wires to create loft face
12:23:10  Traceback (most recent call last):
  File ".local/share/FreeCAD/Mod/CurvedShapes/./CurvedArray.py", line 211, in onChanged
    self.execute(fp)
  File ".local/share/FreeCAD/Mod/CurvedShapes/./CurvedArray.py", line 190, in execute
    self.makeRibs(prop)
  File ".local/share/FreeCAD/Mod/CurvedShapes/./CurvedArray.py", line 116, in makeRibs
    obj.Shape = CurvedShapes.makeSurfaceSolid(ribs, obj.Solid)
  File ".local/share/FreeCAD/Mod/CurvedShapes/./CurvedShapes.py", line 193, in makeSurfaceSolid
    loft = Part.makeLoft(wiribs)
<class 'Part.OCCError'>: 16Standard_Failure Need at least two vertices, edges or wires to create loft face
```
this only happens when the file is first loaded and onChanged is called on document load - not on any later change or forced recompute.

**Comment by AIRCAP** [comment]
the error happens because the array "wiribs" generated from the to be generated ribs is empty - it can't make a loft from no shapes. question is why are the shapes empty on load?

**Comment by AIRCAP** [comment]
ribs is empty because `self.makeRibRotate()` in CurvedArray returns "None" and doesn't add any ribs to the array

**Comment by AIRCAP** [comment]
which is because the calculated positionvectors are either "inf" or "nan" -- the reason seems this:
when makeRibs is called, 
print(obj.Hullcurves[0].Shape.BoundBox) gives
BoundBox (1.79769e+308, 1.79769e+308, 1.79769e+308, -1.79769e+308, -1.79769e+308, -1.79769e+308)

in this case - on load time - running tessellate on the shape does not help, apparently the object isn't yet fully initialized (thus the infinite bounding box) and it cannot be tesselated.  my suggestion would be to make sure execute() is not called when the document first loads, it might be better to just mark it as dirty if any property changes are triggert to force a later recompute

**Comment by AIRCAP** [comment]
I did some more reading. The issue is that "execute()" is called from "OnChanged()" -- this is not supposed to happen - onChanged is only supposed to do crucial internal maintenance (such as checking that all properties are initialized) - execute is run by freecad later to update and recompute "dirty" (changed) objects  -- usually that happens automatically unless the user disables automatic recomputes - but it should not be implicit in the WorkBench

**Comment by chbergmann** [comment]
Thank you for your contribution to fix this
