### ISSUE TITLE
Error message "Object of type FeaturePython is not JSON serializable" when saving a file with CurvedShapes in it

### ISSUE THREAD

**Issue by AIRCAP** [chbergmann/CurvedShapesWorkbench#32]
When saving a file with CurvedShapes in it in FreeCAD, an error message appears. The file is still saved correctly.
This also happens when FreCAD makes its crash-recovery save every 15 minutes:

```
10:54:11  PropertyPythonObject::toString(): failed for <class 'CurvedSegment.CurvedSegmentViewProvider'>
10:54:11  Traceback (most recent call last):
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
<class 'TypeError'>: Object of type FeaturePython is not JSON serializable
```

**Comment by AIRCAP** [comment]
Note: that was with freecad 0.21.2

it seems the issue is the if then else block in the view providers:
```
   if (FreeCAD.Version()[0]+'.'+FreeCAD.Version()[1]) >= '0.22':
        def loads(self, state):
            return None

        def dumps(self):
            return None

    else:
        def __getstate__(self):
            return None

        def __setstate__(self,state):
            return None
```

Comparing to other mods, the fix seems to be to simply provide all 4 functions:
```
    def loads(self, state):
        return None

    def dumps(self):
        return None

    def __getstate__(self):
        return None

    def __setstate__(self,state):
        return None

```

**Comment by chbergmann** [comment]
Thank you for your contribution to fix this
