### ISSUE TITLE
"Twist Reverse"  on same-shape part causes part crash

### ISSUE THREAD

**Issue by AIRCAP** [chbergmann/CurvedShapesWorkbench#47]
```
11:13:11  Traceback (most recent call last):
  File "~/.local/share/FreeCAD/Mod/CurvedShapes/./CurvedSegment.py", line 105, in execute
    self.makeRibs(fp)
  File "~/.local/share/FreeCAD/Mod/CurvedShapes/./CurvedSegment.py", line 140, in makeRibs
    ribs = makeRibsSameShape(fp, fp.Items, False, makeStartEnd)
  File "~/.local/share/FreeCAD/Mod/CurvedShapes/./CurvedSegment.py", line 278, in makeRibsSameShape
    newpoles.append(vectorMiddlePlane(poles1[p], poles2[p], fraction, plane)-fraction*offset)
<class 'IndexError'>: list index out of range
11:13:11  Recompute failed!
```

this triggers #46 and the part is permanently broken (will never recompute again even if parameters are changed)

my line numbers don't match master, 278 is

```
                else:
                    newpoles.append(vectorMiddlePlane(poles1[p], poles2[p], fraction, plane))

```

the reason is hat reorderpoints() somehow gives not enough points.
(2 out of 8 in the example file)

example file:
[reorderpointsbug.zip](https://github.com/user-attachments/files/17227203/reorderpointsbug.zip)

**Comment by AIRCAP** [comment]
no longer crashes part, can be worked around with forceinterpolation, dunno if it triggers an exception still, leaving open for more tests
